### ISSUE TITLE
samtools stats

### ISSUE THREAD

**Issue by kopardev** [RBL-NCI/iCLIP#100]
https://github.com/RBL-NCI/iCLIP/blob/bd28db9f09064b40ac76d1447694a130a1d35f8b/workflow/Snakefile#L1225

I think this 
```
        samtools view -h {output.merged} \\
            | samtools stats - > {output.samstat}
```
can just be 
```
        samtools stats {output.merged} > {output.samstat}
```

**Comment by slsevilla** [comment]
already complete; unclear which commit this happened
