### ISSUE TITLE
remove manifest checking rule out of Snakefile

### ISSUE THREAD

**Issue by kopardev** [RBL-NCI/iCLIP#103]
-  manifest checking should happen before running the pipeline (even dryrun)
- currently if new contrasts are added to old run, the manifest_check.txt file changes and essentially causes to rerun the entire pipeline from scratch.... need to avoid this.
- manifest script needs improvement 
  - check for existence of fastq files
  - check all samples mentioned in contrasts actually exist
  - check for accidental replicates in the contrast
 
May be rewriting a new python script which can be plugged into the main run-wrapper is required.

**Comment by kopardev** [comment]
This issue actually may be linked to [https://github.com/RBL-NCI/iCLIP/issues/89](https://github.com/RBL-NCI/iCLIP/issues/89)

**Comment by slsevilla** [comment]
completed with commit 62d6ee74a6b837ddf1abd412afef8e914a5fa69a
