### ISSUE TITLE
Replace Novoalign by STAR

### ISSUE THREAD

**Issue by kopardev** [RBL-NCI/iCLIP#106]
* remove novoalign rules
 * replace them with STAR
 * expose appropriate STAR parameters to end-user via config file

**Comment by slsevilla** [comment]
complete with commit 6afd36da159ec8f20c607e866292848f5bc8ade4

**Comment by slsevilla** [comment]
chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://physiology.med.cornell.edu/faculty/skrabanek/lab/angsd/lecture_notes/STARmanual.pdf
