### ISSUE TITLE
Replace iCOUNT with Ultraplex

### ISSUE THREAD

**Issue by kopardev** [RBL-NCI/iCLIP#107]
ultraplex is now installed on biowulf as a module ... did some testing.. it was able to demultiplex, quality trim and remove adapter (all in one step) for the 520+ milllion read fastq file (FlagRo1hr_S1_R1_001.fastq.gz from latest Sohyoung sample) in < 20 minutes with 56 core node. Chill, Samantha (NIH/NCI) [C] Check /data/RBL_NCI/Wolin/mESC_clip_4/manifests/ultraplex_testing/FlagRo1hr_ultraplex_output for details. the script run_ultraplex.sh has all the paramters I used.... we need to get this in the pipeline ASAP!!! These are huge savings.... No more Scatter + Gather.

**Comment by slsevilla** [comment]
Testing params:
- used test_2 for all tests (1 multiplexed sample, 2 project samples)

Documentation:
- iCount demultiplex: https://icount.readthedocs.io/en/latest/_modules/iCount/demultiplex.html
- Ultraplex: https://github.com/ulelab/ultraplex 

Reasoning: 
- Demultiplexing was taking a significant amount of time per sample. Seeking a comparable tool that would allow for an increase in speed.

Results:
- Time: Ultraplex significantly reduced the run-time for this test set.
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-1f5d4cba-7fff-87be-f373-21f444de5128">

  | iCOUNT | ULTRAPLEX
-- | -- | --
Time | 25.5 hours | 1.15 hours

</b>
- Barcodes: No significant difference was noted between methods, where the first image represents iCount and the second Ultraplex.

![image](https://user-images.githubusercontent.com/20726305/168878625-1bea5065-f8f5-4235-9ad5-f2841f00dbdf.png)

![image](https://user-images.githubusercontent.com/20726305/168878778-2c0a0ac6-1e0f-4d81-8a0a-09b5fb0fc5e0.png)

**Comment by slsevilla** [comment]
completed with commit a52329efa19941ddac61daf1080634ca1741d610
