### ISSUE TITLE
DE issues with Marco's run 8-09-21-HaCaT_fCLIP_v2.0

### ISSUE THREAD

**Issue by slsevilla** [RBL-NCI/iCLIP#127]
Marco asked me to review the DE results from this run and I have found a few issues.

# Summary
Completed contrasts:
- WT_fCLIP_vs_KO_fCLIP 
- WT_fCLIP_vs_WT-NOPFA  

Problematic contrasts:
- WT_fCLIP_vs_Y5KO_fCLIP
- Y5KO_fCLIP_vs_KO_fCLIP

Three issues observed:
1. Issue with memory
2. Float division by Zero
3. Zero-size array

# Issues expanded
## 1. Issue with memory
Contrast: Contrast WT_fCLIP_vs_Y5KO_fCLIP
Strand: N
Error file: /data/RBL_NCI/Wolin/8-09-21-HaCaT_fCLIP_v2.0/log/20220804_1158/21b_MANORM_analysis.44956591.group_id=WT_fCLIP_vs_Y5KO_fCLIP,strand=N.err

## 2. Float division by Zero
Contrast: Contrast WT_fCLIP_vs_Y5KO_fCLIP
Strand: P
Error file: /data/RBL_NCI/Wolin/8-09-21-HaCaT_fCLIP_v2.0/log/20220804_1158/21b_MANORM_analysis.44954793.group_id=WT_fCLIP_vs_Y5KO_fCLIP,strand=P.err
```
INFO     08/04/2022 14:21: # MAnorm Arguments:
INFO     08/04/2022 14:21: # Name of sample1 = WT_fCLIP
INFO     08/04/2022 14:21: # Name of sample2 = Y5KO_fCLIP
INFO     08/04/2022 14:21: # Peaks file of sample1 = WT_fCLIP_ALLreadPeaks_forMANORM_P.bed
INFO     08/04/2022 14:21: # Peaks file of sample2 = Y5KO_fCLIP_ALLreadPeaks_forMANORM_P.bed
INFO     08/04/2022 14:21: # Reads file of sample1 = WT_fCLIP_ReadsforMANORM_P.bed
INFO     08/04/2022 14:21: # Reads file of sample2 = Y5KO_fCLIP_ReadsforMANORM_P.bed
INFO     08/04/2022 14:21: # Reads shift size of sample1 = 0
INFO     08/04/2022 14:21: # Reads shift size of sample2 = 0
INFO     08/04/2022 14:21: # Peak width to extend from summit = 50
INFO     08/04/2022 14:21: # Summit-to-summit distance cutoff = 25
INFO     08/04/2022 14:21: # Output directory = /data/RBL_NCI/Wolin/8-09-21-HaCaT_fCLIP_v2.0/05_demethod/02_analysis/WT_fCLIP_vs_Y5KO_fCLIP/WT_fCLIP_vs_Y5KO_fCLIP_P/
INFO     08/04/2022 14:21: Step1: Loading input data
INFO     08/04/2022 14:21: 69158 peaks are loaded from WT_fCLIP_ALLreadPeaks_forMANORM_P.bed
INFO     08/04/2022 14:21: 4017 peaks are loaded from Y5KO_fCLIP_ALLreadPeaks_forMANORM_P.bed
INFO     08/04/2022 14:28: 226870510 reads are loaded from WT_fCLIP_ReadsforMANORM_P.bed
INFO     08/04/2022 14:29: 12188984 reads are loaded from Y5KO_fCLIP_ReadsforMANORM_P.bed
INFO     08/04/2022 14:29: Step2: Classifying peaks by overlap
INFO     08/04/2022 14:29: WT_fCLIP: 69143(unique) 15(common)
INFO     08/04/2022 14:29: Y5KO_fCLIP: 4002(unique) 15(common)
INFO     08/04/2022 14:29: Merged common peaks: 15
INFO     08/04/2022 14:29: Step3: Performing overlap enrichment test
INFO     08/04/2022 16:58: Overlapping peaks in random simulation: mean:18.0636 std:4.30485249922
INFO     08/04/2022 16:58: Fold Change: 0.884561829218
INFO     08/04/2022 16:58: Step4: Calculating the read densities
INFO     08/04/2022 16:58: Step5: Fitting normalization model
/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/statsmodels/regression/linear_model.py:1510: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid
/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/statsmodels/robust/norms.py:190: RuntimeWarning: invalid value encountered in less_equal
  return np.less_equal(np.fabs(z), self.t)
/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/statsmodels/robust/robust_linear_model.py:278: RuntimeWarning: invalid value encountered in divide
  self.weights = self.M.weights(wls_results.resid/self.scale)
/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/numpy/linalg/linalg.py:1876: RuntimeWarning: invalid value encountered in greater
  large = s > cutoff
/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/numpy/lib/function_base.py:3250: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/statsmodels/robust/norms.py:267: RuntimeWarning: invalid value encountered in less_equal
  return np.less_equal(np.fabs(z), self.t)
/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/statsmodels/robust/robust_linear_model.py:426: RuntimeWarning: invalid value encountered in double_scalars
  k = 1 + (self.df_model+1)/self.nobs * var_psiprime/m**2
Traceback (most recent call last):
  File "/usr/local/apps/manorm/1.1.4/manorm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/manorm/cmdline.py", line 95, in main
    full_output=full_output, name1=name1, name2=name2, output_name=output_name)
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/manorm/workflow.py", line 59, in main
    ma.fit_model(summit_dis_cutoff)
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/manorm/core.py", line 105, in fit_model
    self.ma_model = sm.RLM(y, x).fit().params
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/statsmodels/robust/robust_linear_model.py", line 287, in fit
    self.normalized_cov_params, self.scale)
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/statsmodels/robust/robust_linear_model.py", line 398, in __init__
    self.cov_params_default = self.bcov_scaled
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/statsmodels/tools/decorators.py", line 97, in __get__
    _cachedval = self.fget(obj)
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/statsmodels/robust/robust_linear_model.py", line 432, in bcov_scaled
    *model.normalized_cov_params
ZeroDivisionError: float division by zero
```
## 3. Zero-size array
Contrast: Contrast Y5KO_fCLIP_vs_KO_fCLIP
Strand: P and N
Error file: /data/RBL_NCI/Wolin/8-09-21-HaCaT_fCLIP_v2.0/log/20220804_1158/21b_MANORM_analysis.44947112.group_id=Y5KO_fCLIP_vs_KO_fCLIP,strand=P.err
Error file: /data/RBL_NCI/Wolin/8-09-21-HaCaT_fCLIP_v2.0/log/20220804_1158/21b_MANORM_analysis.44947090.group_id=Y5KO_fCLIP_vs_KO_fCLIP,strand=N.err

```
INFO     08/04/2022 12:25: # MAnorm Arguments:
INFO     08/04/2022 12:25: # Name of sample1 = Y5KO_fCLIP
INFO     08/04/2022 12:25: # Name of sample2 = KO_fCLIP
INFO     08/04/2022 12:25: # Peaks file of sample1 = Y5KO_fCLIP_ALLreadPeaks_forMANORM_P.bed
INFO     08/04/2022 12:25: # Peaks file of sample2 = KO_fCLIP_ALLreadPeaks_forMANORM_P.bed
INFO     08/04/2022 12:25: # Reads file of sample1 = Y5KO_fCLIP_ReadsforMANORM_P.bed
INFO     08/04/2022 12:25: # Reads file of sample2 = KO_fCLIP_ReadsforMANORM_P.bed
INFO     08/04/2022 12:25: # Reads shift size of sample1 = 0
INFO     08/04/2022 12:25: # Reads shift size of sample2 = 0
INFO     08/04/2022 12:25: # Peak width to extend from summit = 50
INFO     08/04/2022 12:25: # Summit-to-summit distance cutoff = 25
INFO     08/04/2022 12:25: # Output directory = /data/RBL_NCI/Wolin/8-09-21-HaCaT_fCLIP_v2.0/05_demethod/02_analysis/Y5KO_fCLIP_vs_KO_fCLIP/Y5KO_fCLIP_vs_KO_fCLIP_P/
INFO     08/04/2022 12:25: Step1: Loading input data
INFO     08/04/2022 12:25: 4017 peaks are loaded from Y5KO_fCLIP_ALLreadPeaks_forMANORM_P.bed
INFO     08/04/2022 12:25: 2569 peaks are loaded from KO_fCLIP_ALLreadPeaks_forMANORM_P.bed
INFO     08/04/2022 12:26: 12188984 reads are loaded from Y5KO_fCLIP_ReadsforMANORM_P.bed
INFO     08/04/2022 12:26: 17947842 reads are loaded from KO_fCLIP_ReadsforMANORM_P.bed
INFO     08/04/2022 12:26: Step2: Classifying peaks by overlap
INFO     08/04/2022 12:26: Y5KO_fCLIP: 4017(unique) 0(common)
INFO     08/04/2022 12:26: KO_fCLIP: 2569(unique) 0(common)
INFO     08/04/2022 12:26: Merged common peaks: 0
INFO     08/04/2022 12:26: Step3: Performing overlap enrichment test
INFO     08/04/2022 12:33: Overlapping peaks in random simulation: mean:1.0539 std:0.254940757824
INFO     08/04/2022 12:33: Fold Change: 0.0
INFO     08/04/2022 12:33: Step4: Calculating the read densities
INFO     08/04/2022 12:33: Step5: Fitting normalization model
Traceback (most recent call last):
  File "/usr/local/apps/manorm/1.1.4/manorm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/manorm/cmdline.py", line 95, in main
    full_output=full_output, name1=name1, name2=name2, output_name=output_name)
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/manorm/workflow.py", line 59, in main
    ma.fit_model(summit_dis_cutoff)
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/manorm/core.py", line 103, in fit_model
    x = sm.add_constant(a_values[mask])
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/statsmodels/tools/tools.py", line 279, in add_constant
    is_nonzero_const = np.ptp(x, axis=0) == 0
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2224, in ptp
    return _methods._ptp(a, axis=axis, out=out, **kwargs)
  File "/usr/local/Anaconda/envs_app/manorm/1.1.4/lib/python2.7/site-packages/numpy/core/_methods.py", line 153, in _ptp
    umr_maximum(a, axis, None, out, keepdims),
ValueError: zero-size array to reduction operation maximum which has no identity
```

## Solutions
1. Issue with memory
Solution: Will increase max memory for this rule

2. Float division by Zero

3. Zero-size array

**Comment by phoman14** [comment]
For 3. Zero-size array MAnorm correctly errored out because there is no overlap between samples. However we should add a work around if the one strand does have overlap but the other does not. 


I am not sure yet why 2. Float division by Zero error is occurring. There is overlap (15 peaks) But it is not able to normalize data. Maybe there are not enough reads under each peak but I will have to look further. 


I also noticed that the reports were not created for the contrasts that ran correctly, we should modify snakemake to generate report even if other contrasts fail.

**Comment by slsevilla** [comment]
Problem 1 is complete with commit a510334c9b6a7518e6f9ccc87642ffc587e12d60

**Comment by slsevilla** [comment]
I looked into issue #2.

Reviewing v1.8 of the WT/Y5KO comparison showed that parameters for MANORM changed with commit X. In this commit the -m parameter was changed from 1 to 0, and the -w from 1000 to 50. 

v1.8 code
```
manorm
--p1 "/data/RBL_NCI/Wolin/8-09-21HaCaT_fCLIP_v2.0/05_demethod/01_input/WT_fCLIP_ALLreadPeaks_forMANORM_P.bed"
--p2 "/data/RBL_NCI/Wolin/8-09-21-HaCaT_fCLIP_v2.0/05_demethod/01_input/Y5KO_fCLIP_ALLreadPeaks_forMANORM_P.bed"
--r1 "/data/RBL_NCI/Wolin/8-09-21-HaCaT_fCLIP_v2.0/05_demethod/01_input/WT_fCLIP_ReadsforMANORM_P.bed"                 --r2 "/data/RBL_NCI/Wolin/8-09-21-HaCaT_fCLIP_v2.0/05_demethod/01_input/Y5KO_fCLIP_ReadsforMANORM_P.bed"
--s1 0
--s2 0
-p 1
-d 25
-n 10000
-s
-o /data/RBL_NCI/Wolin/8-09-21-HaCaT_fCLIP_v2.0/05_demethod/02_analysis/WT_fCLIP_vs_Y5KO_fCLIP/WT_fCLIP_vs_Y5KO_fCLIP_P/
--name1 WT_fCLIP
--name2 Y5KO_fCLIP
```

I re-ran the current dataset with these reverted parameters, and still received a float division by zero error. It appears the issue merged common peaks, which is extremely low in v2.0, despite similar peak values.

v2.0
```
INFO     08/22/2022 10:32: Step2: Classifying peaks by overlap
INFO     08/22/2022 10:32: WT_fCLIP: 69143(unique) 15(common)
INFO     08/22/2022 10:32: Y5KO_fCLIP: 4002(unique) 15(common)
INFO     08/22/2022 10:32: Merged common peaks: 15
```
v1.8
```
INFO     01/27/2022 11:35: Step2: Classifying peaks by overlap
INFO     01/27/2022 11:35: WT_fCLIP: 50725(unique) 3713(common)
INFO     01/27/2022 11:35: Y5KO_fCLIP: 1587(unique) 3923(common)
INFO     01/27/2022 11:35: Merged common peaks: 3669
```

Unclear if the issue is with alignment (this was the project that had to be run multiple times to get alignment complete) so the current action plan is to re-do alignment and hope that the project goes to completion.

**Comment by phoman14** [comment]
I have updated the 07_MAnorm_Process.R and 08_MAnormAnnotation.Rmd scripts to check for the MAnorm output files. If They are not found it will run bedrolls intersect to check if any overlaps are found between the samples of interest. The resulting bed files will be in the output MAnorm folder. If there are no overlaps the Markdown report will generate an Error  "MAnorm did not generate output table: Overlaps not found between samples", If overlaps are found it will report an Error "MAnorm did not generate output table: MAnorm Normalization Error"

**Comment by slsevilla** [comment]
This project required several STAR parameters to get all samples to align (see https://github.com/RBL-NCI/iCLIP/issues/119). In re-processing this project, with the same STAR parameters, MANORM went to completion with no intervention, as reported previously (with significant overlaps between samples). Updates Phil described above were integrated for future projects that may truly have no overlaps.

**Comment by slsevilla** [comment]
v1.8
INFO     08/22/2022 10:32: Step2: Classifying peaks by overlap
INFO     08/22/2022 10:32: WT_fCLIP: 69143(unique) 15(common)
INFO     08/22/2022 10:32: Y5KO_fCLIP: 4002(unique) 15(common)
INFO     08/22/2022 10:32: Merged common peaks: 15

v2.0 - varying params
INFO     01/27/2022 11:35: Step2: Classifying peaks by overlap
INFO     01/27/2022 11:35: WT_fCLIP: 50725(unique) 3713(common)
INFO     01/27/2022 11:35: Y5KO_fCLIP: 1587(unique) 3923(common)
INFO     01/27/2022 11:35: Merged common peaks: 3669

v2.0 - optimized STAR
INFO     08/29/2022 09:17: Step2: Classifying peaks by overlap
INFO     08/29/2022 09:17: WT_fCLIP: 5058(unique) 2493(common)
INFO     08/29/2022 09:17: Y5KO_fCLIP: 3318(unique) 2496(common)
INFO     08/29/2022 09:17: Merged common peaks: 2488

**Comment by slsevilla** [comment]
Determined that the wrong species was run - will correct to hg38 and re-run.

**Comment by slsevilla** [comment]
After re-running, failure seen with WT and Y5KO samples. 
```
EXITING because of fatal ERROR: not enough memory for BAM sorting: 
SOLUTION: re-run STAR with at least --limitBAMsortRAM 50297600554
```

Attempted to use--limitBAMsortRAM 50297600554 parameter, however, this still resulted in an errorL
```
EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: Expected bin size=38165457492 ; size on disk=35614281728 ; bin number=48
```

Attempting to run test with and without -o-utBAMsortingBinsN 200, as discussed here: https://github.com/alexdobin/STAR/issues/870

Test1: --limitBAMsortRAM 41143265264
Test2: --outBAMsortingBinsN 200 
test3: --outBAMsortingBinsN 200 --limitBAMsortRAM 41143265264

If these do not work, will need to remove bam sorting from STAR and replace controls with samtools for all samples.

**Comment by slsevilla** [comment]
Test 1-3 worked successfully for sample WT_fCLIP, however, the same issues are still being observed with Y5KO_fCLIP.

Additional tests have been deployed for this sample.
4) --outBAMsortingBinsN 400
5) --outBAMsortingBinsN 600
6) --outBAMsortingBinsN 800
7) --outBAMsortingBinsN 400 --limitBAMsortRAM 41143265264
8) --outBAMsortingBinsN 600 --limitBAMsortRAM 41143265264
9) --outBAMsortingBinsN 800 --limitBAMsortRAM 41143265264

**Comment by slsevilla** [comment]
All errors completed - results delivered to PI without issue
