### ISSUE TITLE
include output of unmapped reads

### ISSUE THREAD

**Issue by slsevilla** [RBL-NCI/iCLIP#58]
create bam file of unmapped reads for browsing in case-based scenarios

updated documentation with file location

**Comment by slsevilla** [comment]
unmapped reads are being filtered with step: 
            samtools view {input.f1} | awk '{{ if (($4 == 1 && $6!~/^[0-9]I/ && $1~/:/ )||($4 > 1 && $1~/:/ )) {{ print }} }}' > {output.g1};

update command to include || $4 == 0 to include unmapped reads

**Comment by slsevilla** [comment]
resolved with commit a48054a492e3cf7ae7b4b6cb5414c5625cc9bcd0

**Comment by slsevilla** [comment]
Unmapped reads are being removed in splice_aware fork during genomic coordinate conversion

will need to merge files from join(out_dir,'04_sam_splice','{sp_st}.split.{n}.splice.final.sam') and convert to BAM file to incorporate all reads for this task

**Comment by kopardev** [comment]
I don't understand how the BAM will not have genomic coordinates. Unmapped reads should have NO coordinates and you are adding them to a BAM which has only aligned reads in genomic coordinates. So, the end result should still be a BAM with aligned and unaligned reads with the aligned reads in genomic coordinates.

**Comment by slsevilla** [comment]
completed with two commits: 
a48054a492e3cf7ae7b4b6cb5414c5625cc9bcd0 includes the unmapped reads in BAM
7d32a9dcf65889a17f993c844386620f53bea5bd adds rule to merge unmapped reads after coordinate conversion
