### ISSUE TITLE
Create indices for new alignment strategies

### ISSUE THREAD

**Issue by slsevilla** [RBL-NCI/iCLIP#74]
Indices are needed for splice unaware, splice aware masked exon, and splice aware unmasked exon pipeline, to recalculate the MAPQ score.

Will need to take bash scripts and merge into snakemake for documentation and ease of regeneration, as needed.

**Comment by slsevilla** [comment]
@phoman14 here is the list of things I need for this:
1) need scripts for 146R, both human and mouse
2) need script rmv_duplicate_splice_junctions.pl, for both human and mouse
3) need alignment info for how this bed (/data/RBL_NCI/Phil/Reference/gtf/mouse/mm10/BK000964.3.bed) was created from this fa (/data/RBL_NCI/Phil/Reference/fasta/mm10/preRibosomal/BK000964.3_TPA_exp.fa)

**Comment by phoman14** [comment]
the rmv_duplicate_splice_junctions.pl are in the MakeTranscriptome... folder for each R length eg. /scratch/homanpj/iCLIP/Index/hg38/MakeTranscriptome_SplicedTransc_46R/rmv_duplicate_splice_junctions.pl

**Comment by slsevilla** [comment]
process completed and now archived with updates to v2.0
