### ISSUE TITLE
Incorporate DIFFBIND into Pipeline

### ISSUE THREAD

**Issue by slsevilla** [RBL-NCI/iCLIP#92]
- update snakemake config for DE_METHOD - remove any 'MANORM' output names to the output variable of DE_MEHOD
- add rules for 3 new DIFF_BIND - R script for both P and N (2 jobs per contrast); R script for each contrast; RMD script for final report for each contrast
- update annotations scripts and contrast config to include 'samples' and 'background' instead of 'g1' and 'g2'

**Comment by slsevilla** [comment]
1. updated snakemake config for DE_METHOD to include diffbind option
2. updated run_snakemake.sh -p check param to echo "running check"
3. updated 01_check_manifest.py to print diffbind / manorm options to ensure user is satisfied with selection
4. update Snakefile: remove MANORM from dir names, change to demethod, incorporate diffbind_sh file to snakmake rule, add rules for diffbind R scripts
5. update diffbind R script: remove hardcoding, push dir creation / file naming to snakemake, update params, turn off testing default

**Comment by slsevilla** [comment]
Script 11_DIFFBINDv3.R

I'm unsure what this is attempting to show a venn diagram between, as the code is non-functional, but I'm hoping I've figured it out:
```
if(nrow(samples[samples$group%in%samplename,])<=4){
aa=dba_out_consensus
aa$masks[[samplename]]=names(aa$masks[[samplename]])%in%samples[samples$group%in%samplename,'sample']  
jpeg(paste0(directory,'/06_DEP/02_analysis/',samplename,'vs',background,'_DiffBind/Fig_Venn_',strand,'.jpeg'))
dba.plotVenn(aa,mask=aa$masks[[samplename]], bNotDB=T,bDB=F, bGain=F, bLoss=F, bAll=T)
dev.off()
}
```

I assume you were testing it locally because the code as written (if run in order) overwrites the $mask results, which gives you a NULL return, making the code above non-functional. This is the error you get:
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'table' in selecting a method for function '%in%': error in evaluating the argument 'i' in selecting a method for function '[': error in evaluating the argument 'x' in selecting a method for function '%in%': object of type 'closure' is not subsettable
```

I've figure out the reason for this, and probably why you didn't see it. If you only run the first _consensus then it produces the results I think you're expecting:
```
dba_out_consensus <- dba.peakset(dba_out,
                                 consensus=c(DBA_CONDITION),
                                 minOverlap=sample_overlap,
                                 bRetrieve=F)
names(dba_out_consensus$masks[[samplename]])
[1] "WT1_fCLIP" "WT2_fCLIP" "KO1_fCLIP" "KO2_fCLIP" "WT"        "KO"       
```
Which can then matche the list your searching against and run as expected:
```
 sample_df[sample_df$group%in%samplename,'sample']
[1] "WT1_fCLIP" "WT2_fCLIP"
```

But this is not the last call of this variable. If you run the entire code, the names() call produces a NULL and the error:
```
dba_out_consensus <- dba.peakset(dba_out_consensus,
                                 dba_out_consensus$masks[[samplename]],
                                 bRetrieve=T)
names(dba_out_consensus$masks[[samplename]])
[1] NULL
```

If this is the way you've meant the script to run, I've implemented the following upstream:
```
## Identify peaks found in either sample sample_df
dba_out_consensus <- dba.peakset(dba_out,
                                 consensus=c(DBA_CONDITION),
                                 minOverlap=sample_overlap,
                                 bRetrieve=F)

#create sub dba for plotting downstream
dba_sub = dba(dba_out_consensus, mask=dba_out_consensus$masks[[samplename]])

#run again to retrieve report
dba_out_consensus <- dba.peakset(dba_out_consensus,
                                 dba_out_consensus$masks[[samplename]],
                                 bRetrieve=T)
```

And the following downstream:
```
# max number of comparisons venn can perform is 4
if(nrow(sample_df[sample_df$group%in%samplename,])<=4){

  #jpeg(paste0(output_figures,'VennALL_',strand,'.jpeg'))
  dba.plotVenn(dba_sub,mask=dba_sub$masks[[samplename]],
               bNotDB=T,bDB=F, bGain=F, bLoss=F, bAll=T)
  dev.off()
} else{ print("max number of samples were reached")}
```

Which produces the imaged attached. Hopefully this is correct!
![WT_vs_KO_DIFFBINDVennALL_N](https://user-images.githubusercontent.com/20726305/133932178-249363d1-119d-41ba-9942-82ce3458cb1d.jpeg)

**Comment by slsevilla** [comment]
Same with this code chunk:
```
## plot Concensus peak overlap Venn
jpeg(paste0(directory,'/06_DEP/02_analysis/',samplename,'vs',background,'_DiffBind/Fig_Venn_ConcensusCompare_',strand,'.jpeg'))
dba.plotVenn(dba_out_consensus,main='Group Concensus Peak Overlap',
             dba_out_consensus$masks$Consensus,
             bNotDB=T,bDB=F, bGain=F, bLoss=F, bAll=T)
dev.off()
```

In order to fix this, I had to create a second subsetted dba between the two _consensus variables:
```
dba_sub2 = dba(dba_out_consensus, mask=dba_out_consensus$masks$Consensus)
```

I've also added this inside of the if statement, as this has the same constraints as the previous rule. This is the final, functional chunk for venn diagrams:
```
if(nrow(sample_df[sample_df$group%in%samplename,])<=4){

  ## plot peak overlap
  jpeg(paste0(output_figures,'VennALL_',strand,'.jpeg'))
  dba.plotVenn(dba_sub,main='Sample Group Peak Overlap',
               mask=dba_sub$masks[[samplename]],
               bNotDB=T,bDB=F, bGain=F, bLoss=F, bAll=T)
  dev.off()
  
  ## plot Consensus peak overlap
  jpeg(paste0(output_figures,'VennConsensus_',strand,'.jpeg'))
  dba.plotVenn(dba_sub2,main='Group Concensus Peak Overlap',
               mask=dba_sub2$masks$Consensus,
               bNotDB=T,bDB=F, bGain=F, bLoss=F, bAll=T)
  dev.off()
  
} else{ print("max number of samples were reached, unable to perform Venn comparison")}
```

This produces these two images (I've added a title on the first to match the second):
![WT_vs_KO_DIFFBINDVennALL_N](https://user-images.githubusercontent.com/20726305/133932542-c1108303-6762-4d5f-8486-c0e755cab7ec.jpeg)
![WT_vs_KO_DIFFBINDVennConsensus_N](https://user-images.githubusercontent.com/20726305/133932543-2bcbe0b6-6321-4dae-8c2c-b0819e7da2a8.jpeg)

**Comment by slsevilla** [comment]
Unclear code in 11_DIFFBIND_Process.R
```
# if (JoinJunc==T)
if (F) {
  print("Add annotations to Junctions")
  
  DBdata2_anno=Join_Junction_Combine(DBdata2_anno,read_depth,FtrCount_out)
  
# }else{
  
  # #### collapse exon
  # if (condense_exon==T) {
  #   print("Collapse exon")
  #   
  #   DBdata2_anno=Collapse_Exon(DBdata2_anno)
  # }  
} 
```

Should this be set to (for the true statement):
```
if (join_junction==T)
  print("Add annotations to Junctions")
  DBdata2_anno=Join_Junction_Combine(DBdata2_anno,read_depth,FtrCount_out)
  
 }else{
  
  # #### collapse exon
  # if (condense_exon==T) {
  #   print("Collapse exon")
  #   
  #   DBdata2_anno=Collapse_Exon(DBdata2_anno)
  # }  
} 
```
Unclear what we'd run if the join_junction is false. We aren't brining in the collapse exon param, but we could if this is an alternative option.

**Comment by phoman14** [comment]
This whole section should be removed. It was used for troubleshooting and not part of the final script

**Comment by slsevilla** [comment]
diffbind is incorporated and operational
